### ISSUE TITLE
Help users with type search

### ISSUE THREAD

**Issue by camilstaps** [dopefishh/cloogle#18]
It is apparently not obvious to users how to search for types: people search for `a [a] -> [a]` rather than `:: a [a] -> [a]`.

I see two possibilities to help them:

 - Add a help text (easier to implement; but many people wouldn't read it)
 - Make a clever guess if the user is searching for a type. This should happen in the PHP script. For example, when the search string contains spaces it is quite likely that the user is trying to search for a type. Would there be more cases where we could assume the input is a type? Now, only `::` is recognised by the PHP script.

**Comment by KDercksen** [comment]
Spaces and "` -> `" (with surrounding spaces) would be fairly good giveaways. There are really no giveaways when searching for a result-only function, i.e. `someFunction :: a` with search query `a`.

Another possibility is to take a keyword args approach, a la Google. This would allow search queries like `type=a` or `type="a [a] -> a"`. However, this also requires some extra documentation and is not complete intuitive.

**Comment by dopefishh** [comment]
I vote for help or intro text

**Comment by camilstaps** [comment]
I don't think the keyword args approach would be helpful, `::` is basically that and using a keyword won't make people understand it better.

I tend to lean towards help text as well, because it is easy to document. Otherwise, it becomes magic and that can also be confusing. On the other hand, people would have to read the help text if we write it.

There are, by the way, functions that do not take arguments: `getCommandLine` from ArgEnv, several `TypeCode*` from StdDynamic, `zero` and `one`, etc. (http://cloogle.org/#::%20a).

**Comment by KDercksen** [comment]
![](http://koendercksen.com/files/2016-05-20-162019_614x189_scrot.png)

How about adding a link to something like this? Or would you prefer it on the main page somewhere?

**Comment by camilstaps** [comment]
Looks good for me. I would suggest putting it on the main page behind a link (e.g. like [here](https://demo.camilstaps.nl/HebrewClauses/), but without animations). Also, perhaps include an example of both together. And maybe a placeholder `hd :: [a] -> a` or something like that for the input.

PRs are welcome :joy:

**Comment by KDercksen** [comment]
Hehe, I'll create a pull request for this in a minute. Just wanted to check before I submitted anything.

**Comment by dopefishh** [comment]
implemented and merged
