### ISSUE TITLE
Unifier incorrect or unclear

### ISSUE THREAD

**Issue by camilstaps** [dopefishh/cloogle#25]
Searching for `:: (a,b,c) -> (c,b,a)` gives the result `Init :: (l e) -> l e | List (l e)`, with the unifier `c` &rarr; `a`, `(b,c)` &larr; `l`, `a` &larr; `e`.

This unifier is incorrect: it leads to `(a,b,a) -> (a,b,a)` and `(b,c,a) -> (b,c,a)`. The two *can* be unified, but with another unifier: `c` &rarr; `a`, `(a,b)` &larr; `l`, `a` &larr; `e`.

I guess / hope that this is a representation issue and not a unification bug.

**Comment by camilstaps** [comment]
More useful with debugging are perhaps the unifications of the same search with:

* `forever :: (a b) -> a c`: `c` → `a`; `(b, c)` ← `a`; `a` ← `c`; `a` ← `b`
* `id :: a -> a`: `c` → `a`; `(b, c, a)` ← `a`

It seems the first two elements of the tuples in the unifiers should be swapped. Not sure how this generalises for e.g. 4-tuples.

**Comment by dopefishh** [comment]
Maybe we should clarify the arrow notation. Explicitly specify it with words?

**Comment by camilstaps** [comment]
That too, but in this case we should still investigate if the unification actually works here.
