### ISSUE TITLE
Hints for permuted function arguments

### ISSUE THREAD

**Issue by camilstaps** [dopefishh/cloogle#26]
It would be nice if, when a user searches for `a (a -> a) -> [a]`, also `iterate :: (a -> a) a -> [a]` is suggested (although the two cannot be unified). I see two possibilities:

1. Adding a suggestions field which is a list of similar types and the number of results for that search
2. Adding these results directly to the results list, but with higher distance

**Comment by dopefishh** [comment]
There are `n!` permutations for `n` arguments so listing all permutations is a bit too much for bigger functions. I propose to do this for functions under `k` arguments and indeed list the number of results and maybe a preview with names.

**Comment by dopefishh** [comment]
mentioned in other pr's
