### ISSUE TITLE
Add directional unification option

### ISSUE THREAD

**Issue by dopefishh** [dopefishh/cloogle#27]
This will make sure the unification is only one way and sometimes that is handy. searching for `:: a` will then not match everything.

**Comment by camilstaps** [comment]
Can the same not be achieved by giving unifications with functions a high distance?

**Comment by camilstaps** [comment]
It is now possible to search for functions with universally quantified variables, i.e. `A.b: (a -> b) [a] -> [a]` does not return `dropWhile`, while `(a -> b) [a] -> [a]` does.
