### ISSUE TITLE
Reconsidering field names

### ISSUE THREAD

**Issue by camilstaps** [dopefishh/cloogle#31]
Some of the field names in `Request`, `Response` and `Result` do not scale. For example, `Response` has a `data :: [Result]` field, while `Result` is only for functions. This means that types cannot be returned in the `data` field. However, adding a `types` field makes the API inconsistent (we would expect `functions` instead of `data` then).

What would be good types for `Request`, `Response` and `Result` that scale well?

**Note**: this will not be backwards compatible; we should be reluctant with implementing this.

**Comment by camilstaps** [comment]
Perhaps adding a `ResponseData` type would be helpful:

```clean
:: Response = { ...
              , data :: ResponseData
                ...
              }

:: ResponseData = { data_functions :: [FunctionResult]
                  , data_types :: [TypeResult]
                    ...
                  }

:: Result = { library, filename, modul, distance }  // as the old Result

:: FunctionResult :== (Result, FunctionExtras)      // and similar for TypeResult
:: FunctionExtras = { func    :: String             // Some things from the old Result
                    , unifier :: Maybe StrUnifier
                    , cls     :: Maybe ClassResult
                    }
```

**Comment by camilstaps** [comment]
Once we have the API clear, we can merge the typedefs branch and modify CloogleServer and the frontend to allow users to search on type definitions.

**Comment by dopefishh** [comment]
sure

**Comment by camilstaps** [comment]
With the proposed types it wouldn't be possible to sort on distance, so I changed them a bit more. See `CloogleServer.icl` (for now on the typedefs branch) for the implementation (see above commit). From `api.js` it should be deducable how the JSON is generated.

@KDercksen this is relevant to you, it will break cloogle-cli. I plan to deploy this shortly.

**Comment by KDercksen** [comment]
It looks like it shouldn't be too much work to change for me. Thanks for the heads up!

**Comment by camilstaps** [comment]
Merged to master.
