### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by camilstaps** [dopefishh/cloogle#45]
In order to save CPU time and serve requests faster, it could be useful to implement a simple caching scheme. We could create a file for every request, containing the response, and serve that if the request reoccurs. We could furthermore touch the file when it is used, and keep only the newest *n* files in the cache. To generate the filenames, we could use base64 after jsonEncode. It would be best to do this in the Clean backend, because then also requests from elsewhere talking to Clean directly are cached.

Ideas are welcome.

**Comment by dopefishh** [comment]
this can also be done with a caching http proxy like squid. This has to be on webserver level

**Comment by dopefishh** [comment]
This can even be used by default in the docker images:
https://hub.docker.com/r/sameersbn/squid/

**Comment by camilstaps** [comment]
While that would definitely be the easiest way, it would mess up both long term and live statistics, since cached requests would be no longer passed on to the PHP wrapper or the Cloogle server.
