### ISSUE TITLE
Statistics are broken

### ISSUE THREAD

**Issue by thomwiggers** [dopefishh/cloogle#50]
I'm getting a HTTP 403 for https://cloogle.org/stats/

**Comment by camilstaps** [comment]
There are now both live and long-term statistics:
https://cloogle.org/stats/live.html
https://cloogle.org/stats/longterm.html

At some point it would be nice to integrate the two and add some more graphs. That overview can be put on https://cloogle.org/stats/ then.

**Comment by thomwiggers** [comment]
Then perhaps the readme should be updated to reflect this.

**Comment by camilstaps** [comment]
Thanks!
