### ISSUE TITLE
Highlight colouring is very subtle

### ISSUE THREAD

**Issue by peterachten** [dopefishh/cloogle#72]
On my screen and laptop, the chosen hilite colour of a selection within a module is very subtle, which makes it rather hard to find visually. See attached screenshot. Could you consider using a different colour?
![hilite_colour_cloogle](https://cloud.githubusercontent.com/assets/7021261/22461341/297deb44-e7a9-11e6-8d49-3b056bdd2794.png)

**Comment by dopefishh** [comment]
It could be a little darker I guess...

**Comment by camilstaps** [comment]
Perhaps this can be done properly with #73.
