### ISSUE TITLE
DoS protection

### ISSUE THREAD

**Issue by camilstaps** [dopefishh/cloogle#81]
Apparently some students are not mature enough and we need some kind of protection. I'm thinking about protection in the PHP script to allow, for example, only ten requests in ten seconds. We can think about the exact rules.

**Comment by dopefishh** [comment]
We could try limiting the request based on the browser fingerprint and IP in this way others are not bothered by one DoS'er

**Comment by camilstaps** [comment]
The new scheme will block users for a longer period of time (initially 1 second, doubling that up to 1 minute) when they misbehave within 10 minutes from the last time.
