### ISSUE TITLE
otherwise support

### ISSUE THREAD

**Issue by dopefishh** [dopefishh/cloogle#86]
As written in the 2.2 language report `otherwise` is as synonym for `True`. This should be added in the predef of `builddb.icl`.

**Comment by camilstaps** [comment]
It's not a synonym, because `otherwise` can only be used as the last of a series of guards. You cannot write `Start = otherwise`, for example. It is a separate grammar token (see https://svn.cs.ru.nl/repos/clean-compiler/trunk/frontend/scanner.dcl, `OtherwiseToken`).
